# Generated by Django 5.0.1 on 2024-02-29 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('teach_code', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('postion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.position')),
            ],
        ),
    ]
